version: '3.8'

services:
  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

volumes:
  postgres-order-data: